# Generated by Django 5.0.14 on 2026-06-07 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("max_students", models.IntegerField(default=30)),
                ("lecture_days", models.JSONField(blank=True, default=list)),
                (
                    "lecture_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "batches",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration_weeks", models.IntegerField(blank=True, null=True)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("specialization", models.TextField(blank=True, null=True)),
                ("qualification", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Faculty Member",
                "verbose_name_plural": "Faculty Members",
                "db_table": "faculty",
            },
        ),
        migrations.CreateModel(
            name="FacultyFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("topic_explanation", models.IntegerField()),
                ("subject_knowledge", models.IntegerField()),
                ("communication", models.IntegerField()),
                ("punctuality", models.IntegerField()),
                ("overall_rating", models.IntegerField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Faculty Feedback",
                "verbose_name_plural": "Faculty Feedbacks",
                "db_table": "faculty_feedback",
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "reference_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("newspaper", "Newspaper"),
                            ("social_media", "Social Media"),
                            ("friends_relatives", "Friends/Relatives"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reference_other", models.TextField(blank=True, null=True)),
                (
                    "course_interest",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "funnel_stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead/Inquiry"),
                            ("seminar", "Seminar"),
                            ("bootcamp", "Bootcamp"),
                            ("counselling", "Counselling"),
                            ("follow_up_1", "Follow up 1"),
                            ("follow_up_2", "Follow up 2"),
                            ("follow_up_3", "Follow up 3"),
                            ("follow_up_4", "Follow up 4"),
                            ("follow_up_5", "Follow up 5"),
                            ("admission", "Admission"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "db_table": "inquiries",
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.CharField(max_length=100)),
                ("duration_minutes", models.IntegerField(default=90)),
                ("jitsi_room", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lecture",
                "verbose_name_plural": "Lectures",
                "db_table": "lectures",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                ("file_type", models.CharField(blank=True, max_length=100, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Study Material",
                "verbose_name_plural": "Study Materials",
                "db_table": "materials",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_role", models.CharField(max_length=50)),
                ("sender_id", models.UUIDField(blank=True, null=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("batch", "Batch"),
                            ("student", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Read Record",
                "verbose_name_plural": "Notification Read Records",
                "db_table": "notification_reads",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "reference_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("newspaper", "Newspaper"),
                            ("social_media", "Social Media"),
                            ("friends_relatives", "Friends/Relatives"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reference_other", models.TextField(blank=True, null=True)),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submission_text", models.TextField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=512, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("marks_obtained", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Assignment",
                "verbose_name_plural": "Student Assignments",
                "db_table": "student_assignments",
            },
        ),
        migrations.CreateModel(
            name="VideoTutorial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                (
                    "thumbnail_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Video Tutorial",
                "verbose_name_plural": "Video Tutorials",
                "db_table": "video_tutorials",
            },
        ),
        migrations.CreateModel(
            name="BatchStudent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.batch"
                    ),
                ),
            ],
            options={
                "db_table": "batch_students",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100, unique=True)),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("file_path", models.CharField(blank=True, max_length=512, null=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="core.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "db_table": "certificates",
            },
        ),
        migrations.CreateModel(
            name="BatchSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.batch"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
            ],
            options={
                "db_table": "batch_subjects",
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="courses",
            field=models.ManyToManyField(
                related_name="batches", through="core.BatchSubject", to="core.course"
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("max_marks", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
            },
        ),
    ]
