# Generated by Django 5.2.13 on 2026-05-08 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_add_semester_config"),
        ("users", "0013_adminactivitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyLecture",
            fields=[
                (
                    "proxy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for proxy (e.g., Weekend leave, Sick leave, Conference)",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Cancelled", "Cancelled")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(
                        default=False, help_text="Has notification been sent?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_faculty",
                    models.ForeignKey(
                        db_column="original_faculty_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_lectures",
                        to="users.faculty",
                    ),
                ),
                (
                    "proxy_faculty",
                    models.ForeignKey(
                        blank=True,
                        db_column="proxy_faculty_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proxy_lectures_taken",
                        to="users.faculty",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        db_column="slot_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxy_lectures",
                        to="academics.timetableslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy Lecture",
                "verbose_name_plural": "Proxy Lectures",
                "db_table": "proxy_lectures",
                "ordering": ["-created_at"],
            },
        ),
    ]
